[package]
name = "just-lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
lsp-text = "0.3.0"
lspower = { version = "1.5.0", git = "https://github.com/silvanshade/lspower.git" }
ropey = "1.3.2"
tokio = { version = "1.16.1", features = ["full"] }
tree-sitter = "0.25.3"

[dev-dependencies]
pretty_assertions = "1.1.0"
serde_json = "1.0.79"
tower-test = "0.4.0"

[build-dependencies]
cc = "1.2.16"
